//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AidHandSociety
{
    using System;
    using System.Collections.Generic;
    
    public partial class InfoReg
    {
        public int Id { get; set; }
        public Nullable<int> RegNumber { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
        public string BloodGroup { get; set; }
        public string Unit { get; set; }
        public Nullable<System.DateTime> BirthDay { get; set; }
        public Nullable<System.DateTime> DateOfDonation { get; set; }
        public string Gender { get; set; }
        public string SpecificAddress { get; set; }
        public string District { get; set; }
        public string City { get; set; }
        public string Mobile { get; set; }
    }
}
